export const LIST_GAMES = 'LIST_GAMES';
export const LIST_GAMES_PENDING = 'LIST_GAMES_PENDING';
export const LIST_GAMES_SUCCESS = 'LIST_GAMES_SUCCESS';
export const LIST_GAMES_FAILURE = 'LIST_GAMES_FAILURE';

export const FIND_GAME = 'FIND_GAME';
export const FIND_GAME_PENDING = 'FIND_GAME_PENDING';
export const FIND_GAME_SUCCESS = 'FIND_GAME_SUCCESS';
export const FIND_GAME_FAILURE = 'FIND_GAME_FAILURE';