export const LIST_GAMES = 'LIST_GAMES';
export const LIST_GAMES_PENDING = 'LIST_GAMES_PENDING';
export const LIST_GAMES_SUCCESS = 'LIST_GAMES_SUCCESS';
export const LIST_GAMES_FAILURE = 'LIST_GAMES_FAILURE';